
server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace



jwt:
  issuer: jara
  subject: auth
  expires-time: 60 # 3600000 * 1000 1시간  60 * 60
  re-expires-time : 60 #8640
  secret: my-secret